import {Chat} from "./model";

export const mockFolders: string[] = ["All", "friends", "work", "vntu"];

export const mockChats: Chat[] = [
    {
        id: '1',
        nickname: 'Alice',
        lastMessage: 'Hey! How are you?',
        profilePicture: 'https://randomuser.me/api/portraits/women/1.jpg',
        lastMessageTime: '10:00',
        newMessages: 2,
    },
    {
        id: '2',
        nickname: 'Bob',
        lastMessage: 'I’m here already.',
        profilePicture: 'https://randomuser.me/api/portraits/men/2.jpg',
        lastMessageTime: '09:45',
        newMessages: 0,
    },
    {
        id: '3',
        nickname: 'Kate',
        lastMessage: 'Can you send me the photo?',
        profilePicture: 'https://randomuser.me/api/portraits/women/3.jpg',
        lastMessageTime: '09:30',
        newMessages: 1,
    },
    {
        id: '4',
        nickname: 'David',
        lastMessage: 'Sounds good.',
        profilePicture: 'https://randomuser.me/api/portraits/men/4.jpg',
        lastMessageTime: '09:15',
        newMessages: 0,
    },
    {
        id: '5',
        nickname: 'Sophia',
        lastMessage: 'Waiting at the entrance.',
        profilePicture: 'https://randomuser.me/api/portraits/women/5.jpg',
        lastMessageTime: '09:00',
        newMessages: 3,
    },
    {
        id: '6',
        nickname: 'Andrew',
        lastMessage: 'See you soon!',
        profilePicture: 'https://randomuser.me/api/portraits/men/6.jpg',
        lastMessageTime: '08:45',
        newMessages: 0,
    },
    {
        id: '7',
        nickname: 'Emma',
        lastMessage: 'Did you check the news?',
        profilePicture: 'https://randomuser.me/api/portraits/women/7.jpg',
        lastMessageTime: '08:30',
        newMessages: 5,
    },
    {
        id: '8',
        nickname: 'Max',
        lastMessage: 'All good, thanks!',
        profilePicture: 'https://randomuser.me/api/portraits/men/8.jpg',
        lastMessageTime: '08:15',
        newMessages: 0,
    },
    {
        id: '9',
        nickname: 'Olivia',
        lastMessage: 'I’ll let you know later.',
        profilePicture: 'https://randomuser.me/api/portraits/women/9.jpg',
        lastMessageTime: '08:00',
        newMessages: 2,
    },
    {
        id: '10',
        nickname: 'Lucas',
        lastMessage: 'Okay, I’ll call you back.',
        profilePicture: 'https://randomuser.me/api/portraits/men/10.jpg',
        lastMessageTime: '07:45',
        newMessages: 1,
    },
    {
        id: '11',
        nickname: 'Lucas1',
        lastMessage: 'Okay, I’ll call you back.',
        profilePicture: 'https://randomuser.me/api/portraits/men/10.jpg',
        lastMessageTime: '07:45',
        newMessages: 1,
    },
    {
        id: '12',
        nickname: 'Lucas2',
        lastMessage: 'Okay, I’ll call you back.',
        profilePicture: 'https://randomuser.me/api/portraits/men/10.jpg',
        lastMessageTime: '07:45',
        newMessages: 1,
    },
];
