services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    networks:
      - app-network
    env_file:
      - ./backend/.env
    depends_on:
      - database

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - app-network

  database:
    image: postgres:15
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: myuser
      POSTGRES_DB: mydb
    ports:
      - "5432:5433"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    networks:
      - app-network
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

networks:
  app-network:
    driver: bridge
