import {Message} from "./model";


export const mockMessages: Message[] = [
        {
            chatId: "chat1",
            messageId: "m1",
            messageText: "Hey Bob! 👋",
            senderId: "u1",
            senderName: "Alice",
            recipientId: "u2",
            recipientName: "Bob",
            sendingTime: 1692528000000,
            status: "viewed",
        },
        {
            chatId: "chat1",
            messageId: "m2",
            messageText: "Long time no see! How’s everything going?",
            senderId: "u1",
            senderName: "Alice",
            recipientId: "u2",
            recipientName: "Bob",
            sendingTime: 1692528060000,
            status: "viewed",
        },
        {
            chatId: "chat1",
            messageId: "m3",
            messageText: "Hey Alice! All good, thanks 🙂",
            senderId: "u2",
            senderName: "Bob",
            recipientId: "u1",
            recipientName: "Alice",
            sendingTime: 1692528120000,
            status: "viewed",
        },
        {
            chatId: "chat1",
            messageId: "m4",
            messageText: "Just got back from a trip, it was amazing. I’ll tell you everything when we meet.",
            senderId: "u2",
            senderName: "Bob",
            recipientId: "u1",
            recipientName: "Alice",
            sendingTime: 1692528180000,
            status: "viewed",
        },
        {
            chatId: "chat1",
            messageId: "m5",
            messageText: "Wow, sounds awesome! Can’t wait 😄",
            senderId: "u1",
            senderName: "Alice",
            recipientId: "u2",
            recipientName: "Bob",
            sendingTime: 1692528240000,
            status: "viewed",
        },
        {
            chatId: "chat1",
            messageId: "m6",
            messageText: "By the way, did you finish the report for work?",
            senderId: "u1",
            senderName: "Alice",
            recipientId: "u2",
            recipientName: "Bob",
            sendingTime: 1692528300000,
            status: "sent",
        },
        {
            chatId: "chat1",
            messageId: "m7",
            messageText: "Yes, finally submitted it this morning. Took me forever 😅",
            senderId: "u2",
            senderName: "Bob",
            recipientId: "u1",
            recipientName: "Alice",
            sendingTime: 1692528360000,
            status: "viewed",
        },
        {
            chatId: "chat1",
            messageId: "m8",
            messageText: "Haha, I know that feeling! So relieved now?",
            senderId: "u2",
            senderName: "Bob",
            recipientId: "u1",
            recipientName: "Alice",
            sendingTime: 1692528420000,
            status: "viewed",
        },
        {
            chatId: "chat1",
            messageId: "m9",
            messageText: "Absolutely! 😎",
            senderId: "u1",
            senderName: "Alice",
            recipientId: "u2",
            recipientName: "Bob",
            sendingTime: 1692528480000,
            status: "viewed",
        },
        {
            chatId: "chat1",
            messageId: "m10",
            messageText: "Wanna grab coffee later today? I have some ideas to discuss.",
            senderId: "u1",
            senderName: "Alice",
            recipientId: "u2",
            recipientName: "Bob",
            sendingTime: 1692528540000,
            status: "pending",
        },
        {
            chatId: "chat1",
            messageId: "m11",
            messageText: "Sure! 5 pm works?",
            senderId: "u2",
            senderName: "Bob",
            recipientId: "u1",
            recipientName: "Alice",
            sendingTime: 1692528600000,
            status: "viewed",
        },
        {
            chatId: "chat1",
            messageId: "m12",
            messageText: "Perfect. Can’t wait to show you some sketches I made over the weekend.",
            senderId: "u1",
            senderName: "Alice",
            recipientId: "u2",
            recipientName: "Bob",
            sendingTime: 1692528660000,
            status: "sent",
        },
        {
            chatId: "chat1",
            messageId: "m13",
            messageText: "Oh nice! I’ll bring my notebook too, maybe we can brainstorm a bit.",
            senderId: "u2",
            senderName: "Bob",
            recipientId: "u1",
            recipientName: "Alice",
            sendingTime: 1692528720000,
            status: "viewed",
        },
        {
            chatId: "chat1",
            messageId: "m14",
            messageText: "Sounds perfect. By the way, did you see the new trailer for that movie?",
            senderId: "u1",
            senderName: "Alice",
            recipientId: "u2",
            recipientName: "Bob",
            sendingTime: 1692528780000,
            status: "pending",
        },
        {
            chatId: "chat1",
            messageId: "m15",
            messageText: "Yes! Can’t believe how epic it looks. We should go watch it together sometime 🎬",
            senderId: "u2",
            senderName: "Bob",
            recipientId: "u1",
            recipientName: "Alice",
            sendingTime: 1692528840000,
            status: "sent",
        },
    ];